CREATE TABLE [dbo].[Car]
(
	[carId] INT IDENTITY NOT NULL PRIMARY KEY,
	[make] VARCHAR(MAX) NOT NULL,
	[model] VARCHAR(MAX) NOT NULL,
	[year] INT NOT NULL, 
    [licensePlate] VARCHAR(MAX) NOT NULL, 
    [enabled] BIT NOT NULL DEFAULT 1
)
